// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdbAPAYqA8sXTrzhWBQ1X-harW3eRdbYg',
    appId: '1:984740157858:web:8d228ff057e687dbaf7afb',
    messagingSenderId: '984740157858',
    projectId: 'login-auth-test-14404',
    authDomain: 'login-auth-test-14404.firebaseapp.com',
    storageBucket: 'login-auth-test-14404.appspot.com',
    measurementId: 'G-4VNVVM7ZJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhmL_p0VR8zC1lJ6N_5bJ5HN1scb72-Zg',
    appId: '1:984740157858:android:222e31b2dc8a9713af7afb',
    messagingSenderId: '984740157858',
    projectId: 'login-auth-test-14404',
    storageBucket: 'login-auth-test-14404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc2giPTJlXWyp3sGOeCoODXtzQaSeq5Oc',
    appId: '1:984740157858:ios:44681187917dd6a2af7afb',
    messagingSenderId: '984740157858',
    projectId: 'login-auth-test-14404',
    storageBucket: 'login-auth-test-14404.appspot.com',
    iosClientId: '984740157858-c6mlu9ae7vbsmjosic3bcpisrbco23e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc2giPTJlXWyp3sGOeCoODXtzQaSeq5Oc',
    appId: '1:984740157858:ios:44681187917dd6a2af7afb',
    messagingSenderId: '984740157858',
    projectId: 'login-auth-test-14404',
    storageBucket: 'login-auth-test-14404.appspot.com',
    iosClientId: '984740157858-c6mlu9ae7vbsmjosic3bcpisrbco23e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
